image:
  file: .gitpod.Dockerfile
ports:
    - port: 3000
      onOpen: open-preview
tasks:
    - init: >
        cp .env.example .env;
        pipenv install;
        mysql -u root -e "CREATE DATABASE cumple";
        pipenv run init;
        pipenv run migrate;
        pipenv run upgrade;
        pipenv run start;
    - command: python3 welcome.py
